site_name: Citrix Hypervisor Management API Reference
site_description: Citrix Hypervisor Management API Reference
site_title: Developer Documentation
site_url: https://developer-docs.citrix.com

# Copyright
copyright: 'Copyright &copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: https://www.citrix.com/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

# Page tree
nav:
- Versions:
  - 8.1: https://developer-docs.citrix.com/projects/citrix-hypervisor-management-api/en/8.1/
  - 8.0: https://developer-docs.citrix.com/projects/citrix-hypervisor-management-api/en/8.0/
- Citrix Hypervisor Management API Reference: index.md
- Wire Protocol for Remote API Calls: wire-protocol.md
- VM Lifecycle: vm-lifecycle.md
- API Reference: api-ref-autogen.md
- Error Handling: api-ref-autogen-errors.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/
