site_name: Citrix Hypervisor Management API Reference
site_description: Citrix Hypervisor Management API Reference
site_title: Developer Documentation

copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

theme:
  name: null
  custom_dir: material
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png
  
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta

nav:
- Citrix XenServer 7.6 CR Management API Reference: index.md
- Wire Protocol for Remote API Calls: wire-protocol.md
- VM Lifecycle: vm-lifecycle.md
- API Reference: api-ref-autogen.md
- Error Handling: api-ref-autogen-errors.md
